name: Run tests every day

on:
  schedule:
    # 日本時間24時00分
    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild
            -scheme SimpleToDo
            -sdk iphonesimulator
            -configuration Debug
            build

  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild
            -scheme SimpleToDo
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,name=iPhone 11 Pro'
            clean test

  swift-lint:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Lint code using SwiftLint
        run: swiftlint lint --reporter github-actions-logging
